force-app/main/default/objects/GecoJSO__c/GecoJSO__c.object-meta.xml
<CustomObject>
    <label>Geco JSO</label>
    <nameField>
        <displayFormat>JSO-{00000}</displayFormat>
        <label>Geco JSO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Geco JSOs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/GecoJSO__c/fields/ExternalKey__c.field-meta.xml
<CustomField>
    <fullName>ExternalKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GecoJSO__c/fields/JobOrder__c.field-meta.xml
<CustomField>
    <fullName>JobOrder__c</fullName>
    <label>Job Order</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GecoJSO__c/fields/JobSubOrder__c.field-meta.xml
<CustomField>
    <fullName>JobSubOrder__c</fullName>
    <label>Job Sub Order</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GecoTimeBooking__c/GecoTimeBooking__c.object-meta.xml
<CustomObject>
    <label>Geco Time Booking</label>
    <nameField>
        <displayFormat>GTB-{0000000000}</displayFormat>
        <label>Geco Time Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Geco Time Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/GecoTimeBooking__c/fields/BookingDate__c.field-meta.xml
<CustomField>
    <fullName>BookingDate__c</fullName>
    <label>Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/GecoTimeBooking__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GecoTimeBooking__c/fields/ExternalKey__c.field-meta.xml
<CustomField>
    <fullName>ExternalKey__c</fullName>
    <label>External Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GecoTimeBooking__c/fields/GecoJSO__c.field-meta.xml
<CustomField>
    <fullName>GecoJSO__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Geco JSO</label>
    <referenceTo>GecoJSO__c</referenceTo>
    <relationshipLabel>Geco Time Bookings</relationshipLabel>
    <relationshipName>GecoTimeBookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GecoTimeBooking__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>4096</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GecoTimeBooking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CtrGecoTimesheetUpload.cls
public with sharing class CtrGecoTimesheetUpload {

    @AuraEnabled
    public static void saveTimeBookings(List<GecoWrapper> timeBookings){
        
        if(!timeBookings.isEmpty()){
            Integer month = timeBookings.get(0).bookingDate.month();
            resetMonth(month);
        }else{
            return;
        }

        Map<String, GecoJSO__c> jsoMap = new Map<String, GecoJSO__c>();
        List<GecoTimeBooking__c> bookings = new List<GecoTimeBooking__c>();

        for(GecoWrapper booking : timeBookings){
            String key = booking.key;

            GecoJSO__c jso = null;
            if(!jsoMap.containsKey(key)){
                jso = new GecoJSO__c(
                    JobOrder__c = booking.jobOrder,
                    JobSubOrder__c = booking.jobSubOrder,
                    ExternalKey__c = key
                );
                jsoMap.put(key, jso);
            }else{
                jso = jsoMap.get(key);
            }

            bookings.add(new GecoTimeBooking__c(
                BookingDate__c = booking.bookingDate,
                Employee__c = booking.employee,
                GecoJSO__r = new GecoJSO__c(ExternalKey__c = key),
                Hours__c = booking.hours,
                Notes__c = booking.notes,
                Status__c = booking.status
            ));
        }

        Schema.SObjectField externalKey = GecoJSO__c.Fields.ExternalKey__c;

        Database.upsert(jsoMap.values(), externalKey, true, AccessLevel.USER_MODE);
        Database.insert(bookings, true, AccessLevel.USER_MODE);
        
    }

    private static void resetMonth(Integer month){
        delete [SELECT Id FROM GecoTimeBooking__c WHERE CALENDAR_MONTH(BookingDate__c)= :month];
    }

    public class GecoWrapper{
        
        @AuraEnabled
        public String jobOrder {get;set;}

        @AuraEnabled
        public String jobSubOrder {get;set;}
        
        @AuraEnabled
        public Date bookingDate {get;set;}

        @AuraEnabled
        public String employee {get;set;}

        @AuraEnabled
        public Decimal hours {get;set;}

        @AuraEnabled
        public String notes {get;set;}

        @AuraEnabled
        public String status {get;set;}

        @AuraEnabled
        public String key {get;set;}

    }
}